/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Carpeta;
import backend.Documento;
import backend.File;
import backend.FileType;
import backend.PopUpListener;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco Carreras
 */
public class CrearPopUp extends javax.swing.JFrame {

    private PopUpListener listener;
    /**
     * Creates new form CrearPopUp
     */
    public CrearPopUp(PopUpListener listener) {
        this.listener = listener;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        inputTamaño.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        txtTipo = new javax.swing.JLabel();
        inputTamaño = new javax.swing.JTextField();
        selectTipo = new javax.swing.JComboBox<>();
        txtTamaño1 = new javax.swing.JLabel();
        txtExtension = new javax.swing.JLabel();
        inputExtension = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnCrear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setText("Nombre:");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 50));
        jPanel1.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 33, 250, -1));

        txtTipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(0, 0, 0));
        txtTipo.setText("Tipo:");
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, 50));

        inputTamaño.setEnabled(false);
        jPanel1.add(inputTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 81, 250, -1));

        selectTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carpeta", "Documento" }));
        selectTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoActionPerformed(evt);
            }
        });
        jPanel1.add(selectTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, -1));

        txtTamaño1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTamaño1.setForeground(new java.awt.Color(0, 0, 0));
        txtTamaño1.setText("Tamaño:");
        txtTamaño1.setEnabled(false);
        jPanel1.add(txtTamaño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, 50));

        txtExtension.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtExtension.setForeground(new java.awt.Color(0, 0, 0));
        txtExtension.setText("Extensión:");
        txtExtension.setEnabled(false);
        jPanel1.add(txtExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 50));

        inputExtension.setEnabled(false);
        jPanel1.add(inputExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 182, 250, -1));

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, 50));

        btnCrear1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCrear1.setText("CREAR");
        btnCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoActionPerformed
        // TODO add your handling code here:
        Object selectedItem = selectTipo.getSelectedItem();

        // Verifica si el objeto seleccionado no es nulo
        if (selectedItem != null) {
            String selectedString = selectedItem.toString();
            
            boolean esDocumento = selectedString.equals("Documento");
            inputExtension.setEnabled(esDocumento);
            txtExtension.setEnabled(esDocumento);
            inputTamaño.setEnabled(esDocumento);
            txtTamaño1.setEnabled(esDocumento);
            
            if (esDocumento == false) {
                inputExtension.setText("");
                inputTamaño.setText("0");
            }
            
            if(esDocumento == true) {
                inputTamaño.setText("");
            }
        }
    }//GEN-LAST:event_selectTipoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear1ActionPerformed
        // TODO add your handling code here:
        FileType tipo = null;
        
        if(selectTipo.getSelectedItem().toString().equals("Documento")) {
            tipo = FileType.DOCUMENTO;
        }
        
        if(selectTipo.getSelectedItem().toString().equals("Carpeta")) {
            tipo = FileType.CARPETA;
        }
        
        try {
            Integer.parseInt(inputTamaño.getText());
        } catch (NumberFormatException excepcion) {
            JLabel mensaje = new JLabel("Ingrese un numero en el input de tamaño");
            mensaje.setFont(new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, mensaje);
            return ;
        }
        
        // Notificar al listener (Principal)
        if (listener != null) {
            listener.onObjectCreated(inputNombre.getText(), tipo, Integer.parseInt(inputTamaño.getText()), inputExtension.getText());
        }

        this.dispose();
    }//GEN-LAST:event_btnCrear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPopUp(new PopUpListener() {
                @Override
                public void onObjectCreated(String nombre, FileType type, int size, String extension) {
                    // Implementación de prueba
                    
                }

                @Override
                public void onObjectEdited(String nombre, FileType type, int size, String extension, int fileId) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
            }).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear1;
    private javax.swing.JTextField inputExtension;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputTamaño;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selectTipo;
    private javax.swing.JLabel txtExtension;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTamaño1;
    private javax.swing.JLabel txtTipo;
    // End of variables declaration//GEN-END:variables
}
