/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.File;
import backend.FileType;
import backend.PopUpListener;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco Carreras
 */
public class EditarPopUp extends javax.swing.JFrame {
    private File archivoAeditar = null;
    private PopUpListener listener;
    /**
     * Creates new form EditarPopUp
     */
    public EditarPopUp(File archivo, PopUpListener listener) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.listener = listener;
        this.archivoAeditar = archivo;
        this.habilitarInputs();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        inputTamaño = new javax.swing.JTextField();
        txtTamaño1 = new javax.swing.JLabel();
        txtExtension = new javax.swing.JLabel();
        inputExtension = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setText("Nombre:");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 50));
        jPanel1.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 33, 250, -1));

        inputTamaño.setEnabled(false);
        jPanel1.add(inputTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 81, 250, -1));

        txtTamaño1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTamaño1.setForeground(new java.awt.Color(0, 0, 0));
        txtTamaño1.setText("Tamaño:");
        txtTamaño1.setEnabled(false);
        jPanel1.add(txtTamaño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, 50));

        txtExtension.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtExtension.setForeground(new java.awt.Color(0, 0, 0));
        txtExtension.setText("Extensión:");
        txtExtension.setEnabled(false);
        jPanel1.add(txtExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, 40));

        inputExtension.setEnabled(false);
        jPanel1.add(inputExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, -1));

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, 50));

        btnEditar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int tamaño = 0;
        if(this.archivoAeditar.getType().equals(FileType.DOCUMENTO)) {
            try {
                tamaño = Integer.parseInt(inputTamaño.getText());
            } catch (NumberFormatException excepcion) {
                JLabel mensaje = new JLabel("Ingrese un numero en el input de tamaño");
                mensaje.setFont(new Font("Arial", Font.BOLD, 24));
                JOptionPane.showMessageDialog(null, mensaje);
                return ;
            }   
        }
        
        // Notificar al listener (Principal)
        if (listener != null) {
            listener.onObjectEdited(inputNombre.getText(), this.archivoAeditar.getType(), tamaño, inputExtension.getText(), this.archivoAeditar.getId());
        }

        this.dispose();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void habilitarInputs() {
        if(this.archivoAeditar.getType().equals(FileType.DOCUMENTO)) {
            inputExtension.setEnabled(true);
            txtExtension.setEnabled(true);
            inputTamaño.setEnabled(true);
            txtTamaño1.setEnabled(true);
            inputExtension.setText(this.archivoAeditar.getExtension());
            inputTamaño.setText(String.valueOf(this.archivoAeditar.getSize()));
            inputNombre.setText(this.archivoAeditar.getNombre());
        }
        else {
            inputNombre.setText(this.archivoAeditar.getNombre());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPopUp(new File() {}, new PopUpListener() {
                    @Override
                    public void onObjectCreated(String nombre, FileType type, int size, String extension) {
                        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    }

                    @Override
                    public void onObjectEdited(String nombre, FileType type, int size, String extension, int fileId) {
                        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    }
                }).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JTextField inputExtension;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputTamaño;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtExtension;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTamaño1;
    // End of variables declaration//GEN-END:variables
}
