/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author ezeco
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackG = new javax.swing.JPanel();
        jPTop = new javax.swing.JPanel();
        jLExit = new javax.swing.JLabel();
        jPLateral = new javax.swing.JPanel();
        jPBtnEntrar = new javax.swing.JPanel();
        jLIconEntrar = new javax.swing.JLabel();
        jLEntrar = new javax.swing.JLabel();
        jLtitle = new javax.swing.JLabel();
        jLSubTitle = new javax.swing.JLabel();
        jLBGImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setUndecorated(true);

        jPBackG.setBackground(new java.awt.Color(255, 255, 255));
        jPBackG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPTop.setOpaque(false);

        jLExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close.png"))); // NOI18N
        jLExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPTopLayout = new javax.swing.GroupLayout(jPTop);
        jPTop.setLayout(jPTopLayout);
        jPTopLayout.setHorizontalGroup(
            jPTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTopLayout.createSequentialGroup()
                .addContainerGap(746, Short.MAX_VALUE)
                .addComponent(jLExit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPTopLayout.setVerticalGroup(
            jPTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLExit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPBackG.add(jPTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPLateral.setBackground(new java.awt.Color(0, 0, 153));
        jPLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBtnEntrar.setBackground(new java.awt.Color(0, 0, 204));
        jPBtnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPBtnEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPBtnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPBtnEntrarMouseExited(evt);
            }
        });

        jLIconEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Login.png"))); // NOI18N
        jLIconEntrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPBtnEntrar.add(jLIconEntrar);

        jLEntrar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jLEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEntrar.setText("Entrar");
        jPBtnEntrar.add(jLEntrar);

        jPLateral.add(jPBtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 40));

        jLtitle.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLtitle.setForeground(new java.awt.Color(255, 255, 255));
        jLtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtitle.setText("Archivador");
        jPLateral.add(jLtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 40));

        jLSubTitle.setFont(new java.awt.Font("Roboto Thin", 0, 24)); // NOI18N
        jLSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSubTitle.setText("Gestor de Archivos");
        jPLateral.add(jLSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 30));

        jPBackG.add(jPLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 420));

        jLBGImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/biblioteca.jpg"))); // NOI18N
        jPBackG.add(jLBGImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPBtnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBtnEntrarMouseClicked
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jPBtnEntrarMouseClicked

    private void jPBtnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBtnEntrarMouseEntered
        // TODO add your handling code here:
        jPBtnEntrar.setBackground(new java.awt.Color(0, 0, 190));
        jPBtnEntrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPBtnEntrarMouseEntered

    private void jPBtnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBtnEntrarMouseExited
        // TODO add your handling code here:
        jPBtnEntrar.setBackground(new java.awt.Color(0, 0, 204));
    }//GEN-LAST:event_jPBtnEntrarMouseExited

    private void jLExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLBGImage;
    private javax.swing.JLabel jLEntrar;
    private javax.swing.JLabel jLExit;
    private javax.swing.JLabel jLIconEntrar;
    private javax.swing.JLabel jLSubTitle;
    private javax.swing.JLabel jLtitle;
    private javax.swing.JPanel jPBackG;
    private javax.swing.JPanel jPBtnEntrar;
    private javax.swing.JPanel jPLateral;
    private javax.swing.JPanel jPTop;
    // End of variables declaration//GEN-END:variables
}
